### ISSUE TITLE
Proposal to introduce data processor before training the LLM model

### ISSUE THREAD

**Issue by akgunjal** [instructlab/dev-docs#102]
The LLM models are trained and released as a version today for usage. We can also contribute through skills and knowledge. But what we see is if the data contains noise then it will get into the trained model which affects the accuracy of results.

We propose to introduce a smart data processor which does the below operations.
1. Data cleaning to reduce noise
2. Data Contraction
3. Data pre-processing.

This is a piece of code which needs to be injected in the code where training of data is done for the LLM models. Just before the training is done, the given data has to be processed with our proposed data processor which takes care of the above 3 points before returning the processed data. Then the training can be continued as today. This will help to track and remove the noise from data and ensure only the clean data is used for training the LLM models.

**Comment by russellb** [comment]
We don't do training directly on a provided data set. All data used by training is generated data.

Perhaps you're suggesting a method to improve data prior to its use as a knowledge source? That could make sense, though it seems like it'd be done prior to using InstructLab.

**Comment by akgunjal** [comment]
This can be used in two ways as described below.

1. The data used for training model. It works even if its generated data.
2. The data given by users of re-trained model where the data is their custom data to retrain and use the model.

**Comment by russellb** [comment]
Do you have a more concrete ex+ample of using this on generated data? A working real demo using instructlab generated data would be ideal.

**Comment by russellb** [comment]
> Sure. Can you let me know where is the source of instructlab generated data? We can take that as input and show a working demo.

I'm sorry, but no. If you're going to make a proposal like this, you need to be willing to understand and use InstructLab.

Please feel free to open a new proposal when you have a more detailed integration ready to propose.  Thanks!
