### ISSUE TITLE
Create document detailing pre-reqs for an InstructLab CLI 1.0.0

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/dev-docs#157]
We want to make a public statement as to what features/designs/integrations/etc we, as the Maintainer team, want to see in the project prior to a 1.0.0 release

**Comment by khaledsulayman** [comment]
We should probably remove the requirement for a config file and generally clean up that flow

**Comment by RobotSail** [comment]
We will definitely need a *proper* UI before 1.0
