### ISSUE TITLE
Make Governance section examples less vague 

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/dev-docs#91]
https://github.com/instructlab/dev-docs?tab=readme-ov-file#governance isn't very clear in it's examples - the wording here should be updated

**Comment by russellb** [comment]
What may help is adding examples of what counts as a trivial change -- CI fixes, CI dependency updates, minor wording fixes in docs ...

**Comment by lhawthorn** [comment]
This is somewhat related to issue [Community Issue 311](https://github.com/instructlab/community/issues/311) and both should likely be addressed in revamp to governance doc. I will take care of it if @nathan-weinberg does not mind assigning it to me to unbork.

**Comment by nathan-weinberg** [comment]
For context, this was created due to some confusion around creating a new repo in the org - that would be an example of a non-trivial change IMO. I would also include any changes to Org-level GitHub settings, as well as archiving/deleting repos in the org.
